"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/navbar";
import Portal from "@/components/portal";
import SignInForm from "@/components/signInForm";
import SignUpForm from "@/components/signUpForm";
import usePortalStore from "@/state/portal";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const type = usePortalStore((state) => state.type);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16 bg-[#121212]`}
      >
        <NavBar />
        <Portal title={type === "signIn" ? "Sign In" : "Sign Up"}>
          {type === "signIn" ? <SignInForm /> : <SignUpForm />}
        </Portal>
        {children}
      </body>
    </html>
  );
}
